<?php

namespace FrontisBlocks\Config;

use FrontisBlocks\Traits\Singleton;

class BlockList
{
    use Singleton;

    private $blocks = [];

    public function __construct()
    {
        $this->init_blocks();
    }

    private function init_blocks()
    {
        $this->blocks = [
            'container' => [
                'slug' => 'container',
                'title' => 'Container',
                'package' => 'free',
                'category' => 'layout',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/container.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'accordion' => [
                'slug' => 'accordion',
                'title' => 'Accordion',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/accordion.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'accordion-item' => [
                'slug' => 'accordion-item',
                'title' => 'Accordion Item',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/icon.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'true',
            ],
            'advanced-heading' => [
                'slug' => 'advanced-heading',
                'title' => 'Advanced Heading',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'animated-heading' => [
                'slug' => 'animated-heading',
                'title' => 'Animated Heading',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'advanced-button' => [
                'slug' => 'advanced-button',
                'title' => 'Advanced Button',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-button.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'advanced-image' => [
                'slug' => 'advanced-image',
                'title' => 'Advanced Image',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-image.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'advanced-navigation' => [
                'slug' => 'advanced-navigation',
                'title' => 'Advanced Navigation',
                'package' => 'free',
                'category' => 'navigation',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-navigation.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'false',
                'child' => 'false',
            ],
            'advanced-video' => [
                'slug' => 'advanced-video',
                'title' => 'Advanced Video',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'Freemium',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-video.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'call-to-action' => [
                'slug' => 'call-to-action',
                'title' => 'Call to Action',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/call-to-action.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'countdown' => [
                'slug' => 'countdown',
                'title' => 'Countdown',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/countdown.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'counter-number' => [
                'slug' => 'counter-number',
                'title' => 'Counter Number',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/counter-number.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'contact-form-7' => [
                'slug' => 'contact-form-7',
                'title' => 'Contact Form 7',
                'package' => 'free',
                'category' => 'form',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/contact-form-7.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'dual-button' => [
                'slug' => 'dual-button',
                'title' => 'Dual Button',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/dual-button.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'features-list' => [
                'slug' => 'features-list',
                'title' => 'Features List',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/features-list.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'flip-box' => [
                'slug' => 'flip-box',
                'title' => 'Flip Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/flip-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'false',
                'child' => 'false',
            ],
            'fluent-form' => [
                'slug' => 'fluent-form',
                'title' => 'Fluent Form',
                'package' => 'free',
                'category' => 'form',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/fluent-form.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'image-gallery' => [
                'slug' => 'image-gallery',
                'title' => 'Image Gallery',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/image-gallery.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'info-box' => [
                'slug' => 'info-box',
                'title' => 'Info Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/info-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'icon-box' => [
                'slug' => 'icon-box',
                'title' => 'Icon Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/icon-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'loop-builder' => [
                'slug' => 'loop-builder',
                'title' => 'Loop Builder',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/info-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'false',
                'child' => 'false',
            ],
            'marquee-carousel' => [
                'slug' => 'marquee-carousel',
                'title' => 'Marquee Carousel',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/slider.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'post-grid' => [
                'slug' => 'post-grid',
                'title' => 'Post Grid',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/post-grid.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'pricing-table' => [
                'slug' => 'pricing-table',
                'title' => 'Pricing Table',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/pricing-table.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'progressbar' => [
                'slug' => 'progressbar',
                'title' => 'Progressbar',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/progressbar.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            // 'post-banner' => [
            //     'slug' => 'post-banner',
            //     'title' => 'Post Banner',
            //     'package' => 'free',
            //     'category' => 'content',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/post-grid.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            'slider' => [
                'slug' => 'slider',
                'title' => 'Slider',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/slider.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'slider-item' => [
                'slug' => 'slider-item',
                'title' => 'Slider Item',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/slider.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'true',
            ],
            'social-icons' => [
                'slug' => 'social-icons',
                'title' => 'Social Icons',
                'package' => 'free',
                'category' => 'social',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/social-icons.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            // 'flip-team-member' => [
            //     'slug' => 'flip-team-member',
            //     'title' => 'Flip Team Member',
            //     'package' => 'free',
            //     'category' => 'content',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/team-member.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            // 'off-canvas-opener' => [
            //     'slug' => 'off-canvas-opener',
            //     'title' => 'Off Canvas Opener',
            //     'package' => 'free',
            //     'category' => 'navigation',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            // 'off-canvas-closer' => [
            //     'slug' => 'off-canvas-closer',
            //     'title' => 'Off Canvas Closer',
            //     'package' => 'free',
            //     'category' => 'navigation',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            // 'timezone' => [
            //     'slug' => 'timezone',
            //     'title' => 'Timezone',
            //     'package' => 'free',
            //     'category' => 'navigation',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            'search' => [
                'slug' => 'search',
                'title' => 'Advanced Search',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/call-to-action.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'false',
                'child' => 'false',
            ],
            // 'social-share' => [
            //     'slug' => 'social-share',
            //     'title' => 'Social Share',
            //     'package' => 'free',
            //     'category' => 'social',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/social-icons.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'false',
            //     'child' => 'false',
            // ],
            // 'social-share-child' => [
            //     'slug' => 'social-share-child',
            //     'title' => 'Social Share Child',
            //     'package' => 'free',
            //     'category' => 'social',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/marquee-carousel.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'false',
            //     'child' => 'false',
            // ],
            'table-of-contents' => [
                'slug' => 'table-of-contents',
                'title' => 'Table of Contents',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'false',
                'child' => 'false',
            ],
            'team-member' => [
                'slug' => 'team-member',
                'title' => 'Team Member',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/team-member.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            'testimonial' => [
                'slug' => 'testimonial',
                'title' => 'Testimonial',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => FB_PLUGIN_URL . 'assets/icons/testimonial.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'child' => 'false',
            ],
            // 'code-block' => [
            //     'slug' => 'code-block',
            //     'title' => 'Code Block',
            //     'package' => 'free',
            //     'category' => 'content',
            //     'badge' => 'free',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/post-grid.svg',
            //     'complete' => 'true',
            // ],
            // 'simple-navigation' => [
            //     'slug' => 'simple-navigation',
            //     'title' => 'Simple Navigation',
            //     'package' => 'free',
            //     'category' => 'content',
            //     'badge' => 'Freemium',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ],
            // 'masonry-testimonial' => [
            //     'slug' => 'masonry-testimonial',
            //     'title' => 'Masonry Testimonial',
            //     'package' => 'free',
            //     'category' => 'content',
            //     'badge' => 'Freemium',
            //     'status' => 'true',
            //     'icon' => FB_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
            //     'doc' => 'https://wpmessiah.com/',
            //     'demo' => 'https://wpmessiah.com/',
            //     'complete' => 'true',
            //     'child' => 'false',
            // ]
        ];
        $this->blocks = apply_filters('frontis/blocks/list', $this->blocks);
    }

    public function get_blocks()
    {
        return $this->blocks;
    }

    public function get_block($slug)
    {
        return isset($this->blocks[$slug]) ? $this->blocks[$slug] : null;
    }

    public function get_default_blocks()
    {
        //now return init blocks
        return $this->blocks;
    }
}